### ISSUE TITLE
[ QoL ] -  Wishlistlite should remain "open" even if it fails to connect

### ISSUE THREAD

**Issue by fcancelinha** [usrme/wishlistlite#30]
Issue : [ Quality of life improvement ] - 2023/07
---

Wishlistlite closes or exits to the terminal prompt if it fails to connect or ping a host, it would be better if it remained "open"  to address the problem or remove the bad host.

Behavior
---

Add a dummy unreachable host to the config , and attempt to connect to it. The application exits.

**Comment by usrme** [comment]
Thank you for the issue! A couple of thoughts.

For a failure to ping, I could absolutely leverage the same area of the interface to display the error:

![image](https://github.com/usrme/wishlistlite/assets/5902545/bfc3af25-6000-4b55-9a87-8d6539c5029d)

And something similar for when you can't connect, but potentially limiting the lines of output to just the first:

![image](https://github.com/usrme/wishlistlite/assets/5902545/6ef02f2d-50b7-4f1f-8c51-70e302825821)

And then leave the program open in both cases, _but_ you'd have nothing actionable to do besides removing the host from the Recents view if you had connected to it in the past. The functionality to remove the host from the underlying SSH configuration has never been there unfortunately.

Implementing what is shown above shouldn't be too hard (famous last words), but if you want to leave Wishlist Lite open and either edit the list of hosts directly and have it be reflected in the actual SSH configuration, or maybe edit the SSH configuration outside of Wishlist Lite and have it instead be reloaded into the program, then that should be tracked in a separate issue.

**Comment by fcancelinha** [comment]
Thank you for looking into this !  I really appreciate all the work you're doing, this ssh client is really cool.  I will open the separate issue if needed as you mentioned.

**Comment by usrme** [comment]
I've now released v1.10.0 that should hopefully resolve the original issue, at least as far as I tested it. Let me know if you're okay with me closing this issue :bow:

**Comment by fcancelinha** [comment]
It seems to be working wonderfully now, thank you !
